# Unix Makefile for CheapGlk library

# This generates two files. One, of course, is libcheapglk.a -- the library
# itself. The other is Make.cheapglk; this is a snippet of Makefile code
# which locates the cheapglk library.
#
# When you install cheapglk, you must put libcheapglk.a in the lib directory,
# and glk.h, glkstart.h, and Make.cheapglk in the include directory.
#
# The file cgunigen.c was generated by the casemap.py script, but
# that step isn't in the Makefile -- you don't have to re-generate it.
# It's based on Unicode character data, which is not platform-dependent.

# Pick a C compiler.
CC = cc
#CC = gcc -ansi

OPTIONS = -g -Wall

# Detect OpenSSL location
OPENSSL_CFLAGS := $(shell pkg-config --cflags openssl 2>/dev/null)

CFLAGS = $(OPTIONS) $(INCLUDEDIRS) $(OPENSSL_CFLAGS)
LIBS = -lssl -lcrypto

GLKLIB = libcheapglk.a

CHEAPGLK_OBJS =  \
  cgfref.o cggestal.o cgmisc.o cgstream.o cgstyle.o cgwindow.o cgschan.o \
  cgdate.o cgunicod.o main.o gi_dispa.o gi_blorb.o gi_debug.o cgblorb.o \
  cgllm.o

CHEAPGLK_HEADERS = cheapglk.h gi_dispa.h gi_debug.h glk_llm.h

all: $(GLKLIB) Make.cheapglk

cgunicod.o: cgunigen.c

$(GLKLIB): $(CHEAPGLK_OBJS)
	ar r $(GLKLIB) $(CHEAPGLK_OBJS)
	ranlib $(GLKLIB)

cgllm.o: cgllm.c glk_llm.h
	$(CC) $(CFLAGS) -c cgllm.c

Make.cheapglk:
	echo LINKLIBS = $(LIBDIRS) -lssl -lcrypto > Make.cheapglk
	echo GLKLIB = -lcheapglk >> Make.cheapglk

$(CHEAPGLK_OBJS): glk.h $(CHEAPGLK_HEADERS)

# WebAssembly build targets
EMCC = emcc
WASM_CFLAGS = -O2 -s WASM=1 \
	-s ALLOW_MEMORY_GROWTH=1 \
	-DWASM_BUILD

CHEAPGLK_WASM_OBJS = $(CHEAPGLK_OBJS:.o=.wasm.o)

%.wasm.o: %.c
	$(EMCC) $(WASM_CFLAGS) $(INCLUDEDIRS) -c $< -o $@

libcheapglk.wasm.a: $(CHEAPGLK_WASM_OBJS)
	emar rcs libcheapglk.wasm.a $(CHEAPGLK_WASM_OBJS)

wasm: libcheapglk.wasm.a
	@echo "CheapGlk WASM library built. Now run 'make wasm' in ../glulxe"

clean-wasm:
	rm -f *.wasm.o libcheapglk.wasm.a

clean:
	rm -f *~ *.o $(GLKLIB) Make.cheapglk

.PHONY: wasm clean-wasm
